### PR TITLE
Improved configuration

### PR DESCRIPTION
**Pull request by andriipv**
This pull request will contain changes regarding user configuration.

Currently, I moved morse codes definitions into separate files.
Now editable files by user are in user folder:
config.py - previous userConfig.py
morse_code.py - contains definitions of keyboard and mouse morse codes
morse_code_shortcuts.py - contains definitions of morse codes that used in macro mode.
userPinMap.py - it was just moved into user folder.

This is just first attempt so it can be changed in progress.

About languages support.
Typing letters in other languages can work now but predefined strings won't work with non us language set on target device.
Should I add keymaps structures to make predefined strings work with other languages?
And how should we allow user to change keymaps? 
The only options I see now is additional morse command or manually redefining it in config.

### CODE REVIEW

**Comment by willwade** [comment]
that looks good to me. Nice!

re: "Should I add keymaps structures to make predefined strings work with other languages?"

Got any thoughts what that would look like? I cant imagine it.. 

Re: "And how should we allow user to change keymaps?"

I was wondering - do we have say a UK_keymap.json (or py.. ) - file - like we do at https://github.com/AceCentre/RelayKeys/tree/master/cli_keymaps 

and then just add more of them to a keymap directory as needed?
(Keymaps would then be just a user configurable variable. use_keymap = "UK_keymap..")

**Comment by willwade** [comment]
I'm feeling userPinMap needs to go in root - or x80pinMap needs to go in user (or we somehow combine those files). Its jut not going to be a commonly edited file.

**Comment by f1andrew** [comment]
> Got any thoughts what that would look like? I cant imagine it..
> 
> Re: "And how should we allow user to change keymaps?"
> 
> I was wondering - do we have say a UK_keymap.json (or py.. ) - file - like we do at https://github.com/AceCentre/RelayKeys/tree/master/cli_keymaps

Yes, that's will be dictionary in py file or json file, that will be mapping characters to keycodes.



> I'm feeling userPinMap needs to go in root - or x80pinMap needs to go in user (or we somehow combine those files). Its just not going to be a commonly edited file.

ok, I will move it to root.

**Comment by f1andrew** [comment]
> And how should we allow user to change keymaps?
> The only options I see now is additional morse command or manually redefining it in config.

Here I wanted to ask how user will be swapping or switching between available keymaps. 
Editing them will be no problem.

**Comment by willwade** [comment]
I cant see why anyone would swap on the fly - so I just think it needs to be a flag in the config. that answer your question?

**Comment by f1andrew** [comment]
ok, keymap will be chosen in config or something like that.

**Comment by f1andrew** [comment]
I added keymaps for handling predefined strings. For now there are us and uk keymaps.
Keymap can be set here: https://github.com/f1andrew/morAce/blob/1fdbe5b0ae4060a9e767525195cb0166010e63d7/morAce/user/morse_code.py#L4

Also, I changed morse codes structures to be dictionaries.

**Comment by willwade** [comment]
Great - so If Im right it means you could have a macro of say:



".-"     : "$$",


and it would look up dollar sign and send the correct key code for the defined keymap right?

Looks nicer in a dict

**Comment by f1andrew** [comment]
Yes, that's right.

**Comment by willwade** [comment]
Amazing stuff. Thanks!

**Pull request merged**
