### PR TITLE
changing code to work with passive buzzer

### PR DESCRIPTION
**Pull request by f1andrew**

### CODE REVIEW

**Comment by willwade** [comment]
Line 387. Its pin 
board.D13 

rather than A0 for us here. Maybe its best coming from the constants (X80 or other one)

**Comment by willwade** [comment]
Somethings gone really weird with this now. So if I set the pin to D13 in code.py and boot.py - and uncomment the saving lines. It then by default goes to advertise and in the SW_HID mode. I connect and it connects. But then reboots. Then I see MORSE_HID advertised. I pair and connect - but it reboots. And then It doesn't connect again.. I have to remove, restart it all. And back at the beginning. I wonder if my database.txt is causing the issue.

**Comment by f1andrew** [comment]
There is file for defining x80 pins, you can change them here if needed.: https://github.com/AceCentre/morAce/blob/main/morAce/x80PinMap.py

So buzzer got working buzzer pin was set to A0 or D13?

**Comment by f1andrew** [comment]
I can copy x80_constants.py(https://github.com/AceCentre/X80/blob/main/firmware/python-single-switcher-bluetooth/x80_constants.py) to morAce but there pin variables named differently and A0 not defined in that file.

I just need to confirm pinout.
Should it look like this?
morse_button_1 = board.A4         # no pullup
morse_button_2 = board.A3         # pullup
morse_button_3 = board.A2         # pullup
connection_swap_switch = board.A1 # pullup 
mode_swap_switch = board.A0       # pullup
buzzer = board.D13

**Comment by willwade** [comment]
Yeah - we run out. We have a bizarre way of accessing that mode_swap_switch. Give me a monent to figure it out..

**Comment by willwade** [comment]
Ok - short answer - its messy. 
if you do any refactoring to take into account that x80_constants.py can you drop using a switch for mode_swap_switch - we will just use the morse combination. I personally feel thats better anyway

By all means keep the "if x80" lines so someone (like you and me!) can still build and test this on your own setup.

**Comment by willwade** [comment]
> OK - I've figured this out.
> 
> So look at https://github.com/AceCentre/X80/blob/main/firmware/python-single-switcher-bluetooth/x80_constants.py
> 
> I could do with copying this file to make my head not spin. Notice https://github.com/AceCentre/X80/blob/02b79f511b82466cdd60af3de2eb2a4ffc3134ca/firmware/python-single-switcher-bluetooth/x80_constants.py#L15
> 
> I think we just need a way of defining each pin and whether they are pull-up or not. Sorry to mess up this PR as buzzer thing working well :)

So what I was referring to was the PINUP on switch1. But we are already dealing with that here:

https://github.com/AceCentre/morAce/blob/4b72c2a6f47343598267df30dd604ff2bf7c6313/morAce/boot.py#L24

So maybe thats not the problem I was seeing.

**Comment by f1andrew** [comment]
> Ok - short answer - its messy. if you do any refactoring to take into account that x80_constants.py can you drop using a switch for mode_swap_switch - we will just use the morse combination. I personally feel thats better anyway

I can do this but we don't have defined morse code for mode swapping. 
Currently there is morse code only for swapping connections: https://github.com/AceCentre/morAce/blob/4b72c2a6f47343598267df30dd604ff2bf7c6313/morAce/userConfig.py#L84

Alternatively I can make switching mode by using button and swapping connections only by using morse code.

Let me know which way is more preferred.

**Comment by willwade** [comment]
OK So we have

- keyMouseSwitchMorseCode = ".-.--"
- swapBleConnectionMorseCode  = "-.-.--" 
- user_switch = Swaping BLE connection
- user_switch2 = Switching Morse & Switch control


So to clarify - Lets drop user_switch for swapping BLE Connection and make user_switch = Switching Morse & switch control. (because doing a morse combination on this wouldn't really work anyway?)

**Comment by f1andrew** [comment]
> So to clarify - Lets drop user_switch for swapping BLE Connection and make user_switch = Switching Morse & switch control. (because doing a morse combination on this wouldn't really work anyway?)
ok, I will do it this way

**Comment by f1andrew** [comment]
I removed button that was on A0 pin. Now it should work without constant reboots
.

**Comment by willwade** [comment]
Amazing! Hero @f1andrew  ⭐

**Pull request merged**
